### PR TITLE
Refactor Gradle script, allow more customization

### PR DESCRIPTION
**Pull request by sjchmiela**
A complete refactor:
- more object-oriented (not that I actually like it, I find it encapsulates logic a bit better)
- more customization (`projectDir`, `installClosure`, `package` and location of `BasePackageList`)
- better error messages when the number of `MainApplication`s is different than expected
- backwards compatible

### CODE REVIEW

**Review by wkozyra95 — APPROVED** [review]

**Review by tsapeta — APPROVED** [review]

**Comment by rebirthtobi** [comment]
Waiting for this PR

**Comment by sjchmiela** [comment]
Hey all, I haven't been actively working on this PR since I jumped on another project before merging this PR. Out of curiosity, what is your use case of this autolinking script that you would like to see it merged? I didn't think it will solve any particular problems… 😅

**Comment by capezzbr** [comment]
In my case I was facing a similar issue as the one described in https://github.com/unimodules/react-native-unimodules/issues/87 due to my project using a custom folder structure

**Comment by thongxuan** [comment]
Please fix the conflict :((

**Comment by danibonilha** [comment]
Any update on this ? 😬

**Comment by tsapeta** [comment]
Hey all! 👋 
Sadly, this PR is not going to be merged any time. We're planning to roll out a new version of autolinking soon (not later than SDK43). The new version is being rewritten from scratch, with better modules resolving (like node.js) and better support for monorepos and yarn workspaces specifically. I apologize that you've been waiting so long 🙏

**Pull request closed without merging**
